//! # Google Cloud Storage backend
//!
//! Implements [`StorageBackend`] for Google Cloud Storage (GCS) buckets.
//!
//! ## GCS folder emulation
//!
//! GCS is a flat key-value store with no true directory hierarchy, identical
//! to S3 and Azure. DiskDeck emulates folders using the standard GCS conventions:
//!
//! - **Listing**: Uses the GCS JSON API `list` endpoint with `delimiter=/` so
//!   GCS returns `prefixes` (virtual folders) and `items` (files) for a given prefix.
//! - **Creating folders**: Writes a zero-byte object with a trailing-slash key
//!   (e.g., `documents/`).
//! - **Deleting folders**: Lists all objects under the prefix and deletes each
//!   one individually.
//! - **Renaming**: Performed as copy-then-delete because GCS has no native rename.
//!
//! ## Key normalization
//!
//! DiskDeck uses virtual paths with a leading `/` (e.g., `/photos/sunset.jpg`),
//! but GCS keys should not have a leading slash. The [`GcsBackend::normalize_key`]
//! method strips the leading `/` before every API call, and
//! [`GcsBackend::key_to_path`] adds it back when constructing [`Entry`] paths.
//!
//! ## Authentication
//!
//! The backend accepts a GCP service account JSON key as a string. It generates
//! short-lived OAuth2 access tokens by signing JWTs with the service account's
//! RSA private key. Tokens are cached and refreshed automatically when expired.
//!
//! ## HTTP client
//!
//! Uses `reqwest` with `rustls-tls` to avoid an OpenSSL system dependency,
//! making the backend portable across platforms without extra system libraries.

use async_trait::async_trait;
use reqwest::Client;
use serde::Deserialize;
use tokio::sync::RwLock;

use crate::error::DiskDeckError;
use crate::models::entry::Entry;
use crate::models::search::SearchQuery;

use super::{StorageBackend, StorageResult};

/// Base URL for the GCS JSON API v1.
const GCS_API_BASE: &str = "https://storage.googleapis.com";

/// OAuth2 token endpoint for exchanging JWTs for access tokens.
const TOKEN_URL: &str = "https://oauth2.googleapis.com/token";

/// OAuth2 scope required for full GCS read/write access.
const GCS_SCOPE: &str = "https://www.googleapis.com/auth/devstorage.full_control";

/// Service account key fields parsed from the JSON key file.
#[derive(Deserialize)]
struct ServiceAccountKey {
    /// The service account email address (used as JWT issuer).
    client_email: String,
    /// PEM-encoded RSA private key for signing JWTs.
    private_key: String,
}

/// A cached OAuth2 access token with its expiry time.
struct CachedToken {
    /// The Bearer access token string.
    access_token: String,
    /// Unix timestamp (seconds) when this token expires.
    expires_at: i64,
}

/// Google Cloud Storage backend.
///
/// Holds an HTTP client, service account credentials, and a cached access
/// token. All operations are scoped to a single bucket.
pub struct GcsBackend {
    /// The HTTP client for GCS JSON API requests.
    http: Client,
    /// The GCS bucket name this backend operates on.
    bucket: String,
    /// Parsed service account key for token generation.
    service_account: ServiceAccountKey,
    /// Cached OAuth2 access token, refreshed when expired.
    token: RwLock<Option<CachedToken>>,
}

impl GcsBackend {
    /// Creates a GcsBackend from a service account JSON key string.
    ///
    /// The JSON string is the contents of a GCP service account key file
    /// (downloaded from the Cloud Console IAM page).
    ///
    /// # Arguments
    ///
    /// * `bucket` — GCS bucket name.
    /// * `credentials_json` — Full service account JSON key as a string.
    ///
    /// # Errors
    ///
    /// Returns `DiskDeckError::Storage` if the credentials JSON cannot be
    /// parsed or the HTTP client cannot be constructed.
    pub fn new(bucket: &str, credentials_json: &str) -> Result<Self, DiskDeckError> {
        let service_account: ServiceAccountKey =
            serde_json::from_str(credentials_json).map_err(|e| {
                DiskDeckError::Storage(format!("Invalid GCS credentials JSON: {e}"))
            })?;

        let http = Client::builder()
            .build()
            .map_err(|e| DiskDeckError::Storage(format!("Failed to create HTTP client: {e}")))?;

        Ok(Self {
            http,
            bucket: bucket.to_string(),
            service_account,
            token: RwLock::new(None),
        })
    }

    /// Returns a valid OAuth2 access token, refreshing it if expired.
    ///
    /// Tokens are cached and reused until they expire. A new token is
    /// generated by signing a JWT with the service account's RSA key and
    /// exchanging it at the Google OAuth2 token endpoint.
    async fn access_token(&self) -> Result<String, DiskDeckError> {
        // Check if cached token is still valid (with 60s margin)
        {
            let guard = self.token.read().await;
            if let Some(cached) = guard.as_ref() {
                let now = chrono::Utc::now().timestamp();
                if cached.expires_at > now + 60 {
                    return Ok(cached.access_token.clone());
                }
            }
        }

        // Generate a new token
        let now = chrono::Utc::now().timestamp();
        let claims = serde_json::json!({
            "iss": self.service_account.client_email,
            "scope": GCS_SCOPE,
            "aud": TOKEN_URL,
            "iat": now,
            "exp": now + 3600,
        });

        let header = jsonwebtoken::Header::new(jsonwebtoken::Algorithm::RS256);
        let key = jsonwebtoken::EncodingKey::from_rsa_pem(
            self.service_account.private_key.as_bytes(),
        )
        .map_err(|e| DiskDeckError::Storage(format!("Invalid RSA private key: {e}")))?;

        let jwt = jsonwebtoken::encode(&header, &claims, &key)
            .map_err(|e| DiskDeckError::Storage(format!("Failed to sign JWT: {e}")))?;

        let resp = self
            .http
            .post(TOKEN_URL)
            .form(&[
                ("grant_type", "urn:ietf:params:oauth:grant-type:jwt-bearer"),
                ("assertion", &jwt),
            ])
            .send()
            .await
            .map_err(|e| DiskDeckError::Storage(format!("Token request failed: {e}")))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(DiskDeckError::Storage(format!(
                "Token exchange failed ({status}): {body}"
            )));
        }

        #[derive(Deserialize)]
        struct TokenResponse {
            access_token: String,
            expires_in: i64,
        }

        let token_resp: TokenResponse = resp
            .json()
            .await
            .map_err(|e| DiskDeckError::Storage(format!("Failed to parse token response: {e}")))?;

        let cached = CachedToken {
            access_token: token_resp.access_token.clone(),
            expires_at: now + token_resp.expires_in,
        };

        *self.token.write().await = Some(cached);
        Ok(token_resp.access_token)
    }

    /// URL-encodes a GCS object key for use in API URLs.
    fn encode_key(key: &str) -> String {
        urlencoding::encode(key).into_owned()
    }

    /// Strips the leading `/` from a virtual path to produce a valid GCS key.
    ///
    /// Example: `"/photos/sunset.jpg"` -> `"photos/sunset.jpg"`.
    fn normalize_key(path: &str) -> &str {
        path.strip_prefix('/').unwrap_or(path)
    }

    /// Converts a GCS key back to a virtual absolute-style path.
    ///
    /// Example: `"photos/sunset.jpg"` -> `"/photos/sunset.jpg"`.
    fn key_to_path(key: &str) -> String {
        format!("/{}", key)
    }

    /// Extracts the "filename" (last path component) from a GCS key.
    ///
    /// Handles trailing slashes for folder keys.
    /// Example: `"documents/reports/"` -> `"reports"`.
    fn key_name(key: &str) -> String {
        let trimmed = key.trim_end_matches('/');
        trimmed
            .rsplit('/')
            .next()
            .unwrap_or(trimmed)
            .to_string()
    }
}

/// GCS JSON API response for listing objects.
#[derive(Deserialize)]
struct ListObjectsResponse {
    /// Object items at this prefix level (files).
    #[serde(default)]
    items: Vec<GcsObject>,
    /// Common prefixes (virtual folders) when using a delimiter.
    #[serde(default)]
    prefixes: Vec<String>,
    /// Continuation token for paginated results.
    #[serde(rename = "nextPageToken")]
    next_page_token: Option<String>,
}

/// A single GCS object in a list response.
#[derive(Deserialize)]
struct GcsObject {
    /// The object's key (name) within the bucket.
    name: String,
    /// Object size in bytes, as a string.
    #[serde(default)]
    size: Option<String>,
    /// RFC 3339 timestamp of when the object was last modified.
    updated: Option<String>,
}

#[async_trait]
impl StorageBackend for GcsBackend {
    /// Lists entries at the given virtual path using the GCS JSON API with
    /// prefix and delimiter. Prefixes become directory entries; items become
    /// file entries. The prefix object itself is excluded from results.
    async fn list(&self, path: &str) -> StorageResult<Vec<Entry>> {
        let mut prefix = Self::normalize_key(path).to_string();
        if !prefix.is_empty() && !prefix.ends_with('/') {
            prefix.push('/');
        }

        let token = self.access_token().await?;
        let mut entries = Vec::new();
        let mut page_token: Option<String> = None;

        loop {
            let mut url = format!(
                "{}/storage/v1/b/{}/o?prefix={}&delimiter=/",
                GCS_API_BASE,
                urlencoding::encode(&self.bucket),
                urlencoding::encode(&prefix),
            );
            if let Some(ref pt) = page_token {
                url.push_str(&format!("&pageToken={}", urlencoding::encode(pt)));
            }

            let resp = self
                .http
                .get(&url)
                .bearer_auth(&token)
                .send()
                .await
                .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

            if !resp.status().is_success() {
                let status = resp.status();
                let body = resp.text().await.unwrap_or_default();
                return Err(DiskDeckError::Storage(format!(
                    "GCS list failed ({status}): {body}"
                )));
            }

            let list_resp: ListObjectsResponse = resp
                .json()
                .await
                .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

            // Folders (common prefixes)
            for p in &list_resp.prefixes {
                let name = Self::key_name(p);
                if !name.is_empty() {
                    entries.push(Entry {
                        path: Self::key_to_path(p.trim_end_matches('/')),
                        name,
                        size: 0,
                        modified: None,
                        created: None,
                        is_dir: true,
                        permissions: None,
                        mime_type: None,
                    });
                }
            }

            // Files (objects at this prefix level)
            for obj in &list_resp.items {
                // Skip the prefix object itself (the "folder marker")
                if obj.name == prefix {
                    continue;
                }
                let name = Self::key_name(&obj.name);
                if name.is_empty() {
                    continue;
                }
                let size = obj
                    .size
                    .as_deref()
                    .and_then(|s| s.parse::<u64>().ok())
                    .unwrap_or(0);
                let modified = obj.updated.as_deref().and_then(|s| {
                    chrono::DateTime::parse_from_rfc3339(s)
                        .ok()
                        .map(|dt| dt.timestamp())
                });
                let mime = mime_guess::from_path(&name)
                    .first()
                    .map(|m| m.to_string());

                entries.push(Entry {
                    path: Self::key_to_path(&obj.name),
                    name,
                    size,
                    modified,
                    created: None,
                    is_dir: false,
                    permissions: None,
                    mime_type: mime,
                });
            }

            match list_resp.next_page_token {
                Some(pt) => page_token = Some(pt),
                None => break,
            }
        }

        Ok(entries)
    }

    /// Downloads the full contents of a GCS object.
    async fn read(&self, path: &str) -> StorageResult<Vec<u8>> {
        let key = Self::normalize_key(path);
        let token = self.access_token().await?;

        let url = format!(
            "{}/storage/v1/b/{}/o/{}?alt=media",
            GCS_API_BASE,
            urlencoding::encode(&self.bucket),
            Self::encode_key(key),
        );

        let resp = self
            .http
            .get(&url)
            .bearer_auth(&token)
            .send()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(DiskDeckError::Storage(format!(
                "GCS read failed ({status}): {body}"
            )));
        }

        let data = resp
            .bytes()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;
        Ok(data.to_vec())
    }

    /// Uploads bytes as a GCS object, creating or overwriting.
    async fn write(&self, path: &str, data: &[u8]) -> StorageResult<()> {
        let key = Self::normalize_key(path);
        let token = self.access_token().await?;
        let mime = mime_guess::from_path(key)
            .first_or_octet_stream()
            .to_string();

        let url = format!(
            "{}/upload/storage/v1/b/{}/o?uploadType=media&name={}",
            GCS_API_BASE,
            urlencoding::encode(&self.bucket),
            urlencoding::encode(key),
        );

        let resp = self
            .http
            .post(&url)
            .bearer_auth(&token)
            .header("Content-Type", mime)
            .body(data.to_vec())
            .send()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(DiskDeckError::Storage(format!(
                "GCS write failed ({status}): {body}"
            )));
        }

        Ok(())
    }

    /// Deletes a file or "folder" from GCS.
    ///
    /// For folders, lists all objects under the prefix and deletes each one.
    async fn delete(&self, path: &str) -> StorageResult<()> {
        let key = Self::normalize_key(path);
        let token = self.access_token().await?;

        // Check if it's a "folder" by listing with prefix
        let folder_prefix = if key.ends_with('/') {
            key.to_string()
        } else {
            format!("{}/", key)
        };

        let url = format!(
            "{}/storage/v1/b/{}/o?prefix={}&maxResults=1",
            GCS_API_BASE,
            urlencoding::encode(&self.bucket),
            urlencoding::encode(&folder_prefix),
        );

        let resp = self
            .http
            .get(&url)
            .bearer_auth(&token)
            .send()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        let list_resp: ListObjectsResponse = resp
            .json()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        if !list_resp.items.is_empty() {
            // Folder: list all children and delete each
            let mut page_token: Option<String> = None;
            loop {
                let mut list_url = format!(
                    "{}/storage/v1/b/{}/o?prefix={}",
                    GCS_API_BASE,
                    urlencoding::encode(&self.bucket),
                    urlencoding::encode(&folder_prefix),
                );
                if let Some(ref pt) = page_token {
                    list_url.push_str(&format!("&pageToken={}", urlencoding::encode(pt)));
                }

                let list_token = self.access_token().await?;
                let list_resp_inner: ListObjectsResponse = self
                    .http
                    .get(&list_url)
                    .bearer_auth(&list_token)
                    .send()
                    .await
                    .map_err(|e| DiskDeckError::Storage(e.to_string()))?
                    .json()
                    .await
                    .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

                for obj in &list_resp_inner.items {
                    let del_url = format!(
                        "{}/storage/v1/b/{}/o/{}",
                        GCS_API_BASE,
                        urlencoding::encode(&self.bucket),
                        Self::encode_key(&obj.name),
                    );
                    let del_token = self.access_token().await?;
                    self.http
                        .delete(&del_url)
                        .bearer_auth(&del_token)
                        .send()
                        .await
                        .map_err(|e| DiskDeckError::Storage(e.to_string()))?;
                }

                match list_resp_inner.next_page_token {
                    Some(pt) => page_token = Some(pt),
                    None => break,
                }
            }
        } else {
            // Single object deletion
            let del_url = format!(
                "{}/storage/v1/b/{}/o/{}",
                GCS_API_BASE,
                urlencoding::encode(&self.bucket),
                Self::encode_key(key),
            );
            self.http
                .delete(&del_url)
                .bearer_auth(&token)
                .send()
                .await
                .map_err(|e| DiskDeckError::Storage(e.to_string()))?;
        }

        Ok(())
    }

    /// Copies a single object within the same bucket using GCS's server-side
    /// `rewriteObject` API.
    async fn copy(&self, src: &str, dst: &str) -> StorageResult<()> {
        let src_key = Self::normalize_key(src);
        let dst_key = Self::normalize_key(dst);
        let token = self.access_token().await?;

        let url = format!(
            "{}/storage/v1/b/{}/o/{}/rewriteTo/b/{}/o/{}",
            GCS_API_BASE,
            urlencoding::encode(&self.bucket),
            Self::encode_key(src_key),
            urlencoding::encode(&self.bucket),
            Self::encode_key(dst_key),
        );

        let resp = self
            .http
            .post(&url)
            .bearer_auth(&token)
            .send()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(DiskDeckError::Storage(format!(
                "GCS copy failed ({status}): {body}"
            )));
        }

        Ok(())
    }

    /// Renames by copying then deleting, since GCS has no native rename operation.
    async fn rename(&self, src: &str, dst: &str) -> StorageResult<()> {
        self.copy(src, dst).await?;
        self.delete(src).await?;
        Ok(())
    }

    /// Retrieves metadata for a single object using the GCS JSON API.
    ///
    /// MIME type falls back to extension-based guessing if the object's
    /// `contentType` is not available.
    async fn stat(&self, path: &str) -> StorageResult<Entry> {
        let key = Self::normalize_key(path);
        let token = self.access_token().await?;

        let url = format!(
            "{}/storage/v1/b/{}/o/{}",
            GCS_API_BASE,
            urlencoding::encode(&self.bucket),
            Self::encode_key(key),
        );

        let resp = self
            .http
            .get(&url)
            .bearer_auth(&token)
            .send()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(DiskDeckError::Storage(format!(
                "GCS stat failed ({status}): {body}"
            )));
        }

        let obj: GcsObject = resp
            .json()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        let name = Self::key_name(key);
        let size = obj
            .size
            .as_deref()
            .and_then(|s| s.parse::<u64>().ok())
            .unwrap_or(0);
        let modified = obj.updated.as_deref().and_then(|s| {
            chrono::DateTime::parse_from_rfc3339(s)
                .ok()
                .map(|dt| dt.timestamp())
        });
        let mime = mime_guess::from_path(&name)
            .first()
            .map(|m| m.to_string());

        Ok(Entry {
            path: Self::key_to_path(key),
            name,
            size,
            modified,
            created: None,
            is_dir: false,
            permissions: None,
            mime_type: mime,
        })
    }

    /// Checks existence by issuing a metadata request.
    /// Any error (including 404) is treated as "does not exist".
    async fn exists(&self, path: &str) -> StorageResult<bool> {
        match self.stat(path).await {
            Ok(_) => Ok(true),
            Err(_) => Ok(false),
        }
    }

    /// Brute-force search: lists all objects in the bucket and filters by name.
    ///
    /// This is the live-search fallback for unindexed GCS disks. For large
    /// buckets this can be slow; the FTS5 index should be used when available.
    ///
    /// Note: only matches against the filename portion of the key, not the full
    /// path.
    async fn search(&self, query: &SearchQuery) -> StorageResult<Vec<Entry>> {
        let mut entries = Vec::new();
        let pattern = query.pattern.to_lowercase();
        let token = self.access_token().await?;
        let mut page_token: Option<String> = None;

        loop {
            let mut url = format!(
                "{}/storage/v1/b/{}/o",
                GCS_API_BASE,
                urlencoding::encode(&self.bucket),
            );
            let mut has_query = false;
            if let Some(ref pt) = page_token {
                url.push_str(&format!("?pageToken={}", urlencoding::encode(pt)));
                has_query = true;
            }
            // Ensure the URL has at least one query param for proper formatting
            if !has_query {
                url.push_str("?maxResults=1000");
            } else {
                url.push_str("&maxResults=1000");
            }

            let resp = self
                .http
                .get(&url)
                .bearer_auth(&token)
                .send()
                .await
                .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

            if !resp.status().is_success() {
                let status = resp.status();
                let body = resp.text().await.unwrap_or_default();
                return Err(DiskDeckError::Storage(format!(
                    "GCS search failed ({status}): {body}"
                )));
            }

            let list_resp: ListObjectsResponse = resp
                .json()
                .await
                .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

            for obj in &list_resp.items {
                let name = Self::key_name(&obj.name);
                if name.to_lowercase().contains(&pattern) {
                    let size = obj
                        .size
                        .as_deref()
                        .and_then(|s| s.parse::<u64>().ok())
                        .unwrap_or(0);
                    let modified = obj.updated.as_deref().and_then(|s| {
                        chrono::DateTime::parse_from_rfc3339(s)
                            .ok()
                            .map(|dt| dt.timestamp())
                    });
                    let mime = mime_guess::from_path(&name)
                        .first()
                        .map(|m| m.to_string());

                    entries.push(Entry {
                        path: Self::key_to_path(&obj.name),
                        name,
                        size,
                        modified,
                        created: None,
                        is_dir: false,
                        permissions: None,
                        mime_type: mime,
                    });
                }
            }

            match list_resp.next_page_token {
                Some(pt) => page_token = Some(pt),
                None => break,
            }
        }

        Ok(entries)
    }

    /// Creates a "folder" by writing a zero-byte object with a trailing-slash key.
    ///
    /// This is the standard GCS convention for representing empty directories.
    async fn create_dir(&self, path: &str) -> StorageResult<()> {
        let mut key = Self::normalize_key(path).to_string();
        if !key.ends_with('/') {
            key.push('/');
        }

        let token = self.access_token().await?;
        let url = format!(
            "{}/upload/storage/v1/b/{}/o?uploadType=media&name={}",
            GCS_API_BASE,
            urlencoding::encode(&self.bucket),
            urlencoding::encode(&key),
        );

        let resp = self
            .http
            .post(&url)
            .bearer_auth(&token)
            .header("Content-Type", "application/x-directory")
            .body(Vec::<u8>::new())
            .send()
            .await
            .map_err(|e| DiskDeckError::Storage(e.to_string()))?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(DiskDeckError::Storage(format!(
                "GCS create_dir failed ({status}): {body}"
            )));
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_key_strips_leading_slash() {
        assert_eq!(
            GcsBackend::normalize_key("/photos/sunset.jpg"),
            "photos/sunset.jpg"
        );
    }

    #[test]
    fn normalize_key_no_slash() {
        assert_eq!(
            GcsBackend::normalize_key("photos/sunset.jpg"),
            "photos/sunset.jpg"
        );
    }

    #[test]
    fn normalize_key_just_slash() {
        assert_eq!(GcsBackend::normalize_key("/"), "");
    }

    #[test]
    fn normalize_key_empty() {
        assert_eq!(GcsBackend::normalize_key(""), "");
    }

    #[test]
    fn key_to_path_adds_slash() {
        assert_eq!(
            GcsBackend::key_to_path("photos/sunset.jpg"),
            "/photos/sunset.jpg"
        );
    }

    #[test]
    fn key_to_path_empty() {
        assert_eq!(GcsBackend::key_to_path(""), "/");
    }

    #[test]
    fn key_name_simple() {
        assert_eq!(GcsBackend::key_name("photos/sunset.jpg"), "sunset.jpg");
    }

    #[test]
    fn key_name_trailing_slash() {
        assert_eq!(GcsBackend::key_name("documents/reports/"), "reports");
    }

    #[test]
    fn key_name_no_slash() {
        assert_eq!(GcsBackend::key_name("file.txt"), "file.txt");
    }

    #[test]
    fn key_name_empty() {
        assert_eq!(GcsBackend::key_name(""), "");
    }

    #[test]
    fn new_parses_valid_credentials() {
        let creds = serde_json::json!({
            "client_email": "test@project.iam.gserviceaccount.com",
            "private_key": "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA2a2rwplBQLfYHUP8dOKWF0NMmMnOEviVxRbmpKfMFSmBLWfM\nWGNBHRAuHEFhbgLqDaEz+0mS7X5MpVngehAmFOp/XEPzk9GDh2stayv0pxCHCuFZ\nM0JsrMGLB8E1ItUkRkNrX4JqnO/BIIPkIrv4c0vCaJPdATKO+JKZOGRCYF0A2wmy\nY/Fv+hS/XP/e8mSCPB8ZP+M+GxxSjwflWo/M8PL5MYP+oz6k/IR7PI1gr4Yra7Z\njfiMfIFH4hSgLH2tdgGHVGDT7tOPBJ6tatYPMXIC+ps8liJGJPaOLsDqq5IU7aYI\ny1wFGNz8iB8M9fTQWj6GGp4iLHii9v0b1bkCIQIDAQABAoIBAAWHNzriHy1qLa2l\nC/lNc+6bTn4pF5jvPNP2MSWFq1LJkxYvXXc26P+bCZkU68YlSUlHNamVRSCjrXlY\nMT0/4IxVhYmQDEi7FpUq9J4i5KVjsQPv+vO47KXHIBKaB69tJhCfBrqKO8iWjHVi\neIcE2FGBTWMPxqJe6RNmrRLJXFG8Fmadsfab1i+hJuiAqHUfXCB/P1SOIQLF3Fme\na/5/BNGQQ+0OlAPTlBOp/cqyBHf7MH9RhfG2JgUDqHPLsMqaFHkrcX4CqQFE+90M\niI0s7/JA65n86WxNqK8gIC0fCXE3kLK/1h7BQFM1LxY8oHk0TSNPp2VSbAnqmxhVz\nvvCfOHECgYEA7X0bNbBVjK8mPaS3OQab8M7B8Rhe3oVJRPFvjMn8RRnNTMd77EPE\njTp7c0a5RANKqyXc2VagLHm3sHxAw7P+B0sFUJhfaJ3b3hBCfQjgX9M2DiZMHr7m\nIqenI3+CPFdnQ/z4hjmpTH9rBtrFJNoHn+fQaefynREL+aQIe5R+dqkCgYEA6i9J\nCAF6UOlNF5oVy/hXXvMrdIEPe1FfMDOLJz2uGT0p57FPfMLj5sHLDGdFG3cSR0EF\njx8B3F7VfPNmxCq7C7QFBwW3FNiiWzMbm2DQ6AsD10bUujMHPFiH5q8PWd5w8YUH\nwIoxz3m5j2UjERZ0f1t9yLz5g/jzE91YCTWHVWkCgYEAiJ2CVhmjJpA9eNQPFuKH\nz4bOaQ8xeN2gGQ8laO+Cvh1xUGaaMBkhFsBpxCDqp4vhg3pj+hEA/4gJL3i0pPP3\no7C0jL9J/1r/AB3dQPhlXf2OqB/JSlFjn2czYrLiHPSroRCvxwAVKf37GY9z0jLq\nOqj1mWAn/JdhcIbZSaXiYYECgYAcN/kpH4q7EeE+VwF5cB7C+PGvOxMdnMWfTUuE\nebfQMSED9N0buiCjPzOI9EKHJ0k7p12iD5AqknCxsopyJJqWEMB4l/jjplGBJrFC\nYQpCtdFnhb0LNml7WsJ/D/IEBxVxRfIlrMNiPzq+5GWXHXP0SBj3ar8kqaTdl1Ub\nQ6OWIQKBgDXLbJx1P3APMl/B0YNDg3MVg/rDAxkpcHFrM2cFXXhNbsJJkpN0hOF3\n1X0C+khZ07vDGoKO20S6GBVFdW3p4sgYTFG5l7o6bMPnnlPBMNNkdwfSe/0RLHef\nj7g/S0TQgkTM+EGWdE8VfGHhTP+YgNSqma2LbKO8RKYSK2D0XRXC\n-----END RSA PRIVATE KEY-----\n"
        });
        let result = GcsBackend::new("my-bucket", &creds.to_string());
        assert!(result.is_ok());
        let backend = result.unwrap();
        assert_eq!(backend.bucket, "my-bucket");
    }

    #[test]
    fn new_rejects_invalid_json() {
        let result = GcsBackend::new("my-bucket", "not valid json");
        assert!(result.is_err());
    }

    #[test]
    fn new_rejects_missing_fields() {
        let creds = serde_json::json!({ "client_email": "test@example.com" });
        let result = GcsBackend::new("my-bucket", &creds.to_string());
        assert!(result.is_err());
    }

    #[test]
    fn encode_key_handles_special_chars() {
        assert_eq!(GcsBackend::encode_key("path/to/file.txt"), "path%2Fto%2Ffile.txt");
    }

    #[test]
    fn encode_key_handles_spaces() {
        assert_eq!(GcsBackend::encode_key("my file.txt"), "my%20file.txt");
    }
}
