/**
 * @file IPC Contract Types
 *
 * Defines the TypeScript types that mirror the Rust backend models
 * (backend/src/models/). These types are the canonical contract between the
 * Tauri backend and the SolidJS frontend -- every `invoke()` call in
 * `lib/ipc.ts` sends and receives data shaped according to these interfaces.
 *
 * **Relationship to backend:**
 * Each interface here corresponds to a serde-serializable Rust struct.
 * Field names use snake_case to match the JSON wire format produced by serde.
 * If the backend schema changes, these types MUST be updated in lockstep.
 *
 * @module lib/types
 */

/**
 * Supported storage backend types.
 * Each variant maps to a different adapter on the Rust side (local FS, AWS S3,
 * Google Cloud Storage, Azure Blob Storage, SFTP, or FTP).
 */
export type DiskType = "local" | "s3" | "gcs" | "azure" | "sftp" | "ftp";

/**
 * Configuration for a single registered disk (storage backend).
 *
 * @property id         - UUID generated by the backend on creation.
 * @property name       - User-facing display name (e.g. "My Documents").
 * @property disk_type  - Which storage adapter to use.
 * @property config     - Backend-specific key/value pairs (e.g. `{ root: "/home/user" }`
 *                        for local, `{ bucket, region, access_key_id, secret_access_key }`
 *                        for S3, `{ bucket, credentials_json }` for GCS). Values are
 *                        typically strings but may be other JSON types since the Rust
 *                        side uses `serde_json::Value`. The exact keys depend on `disk_type`.
 * @property created_at - ISO 8601 timestamp of when the disk was first added.
 */
export interface DiskConfig {
  id: string;
  name: string;
  disk_type: DiskType;
  config: Record<string, unknown>;
  created_at: string;
}

/**
 * A single file-system entry (file or directory) within a disk.
 *
 * Paths are storage-relative (always start with "/") and use forward-slash
 * separators regardless of the underlying OS.
 *
 * @property path        - Absolute storage-relative path, e.g. "/docs/readme.md".
 * @property name        - Basename of the entry, e.g. "readme.md".
 * @property size        - Size in bytes. 0 for directories.
 * @property modified    - Unix timestamp (seconds) of last modification, or null if unavailable.
 * @property is_dir      - True when the entry is a directory.
 * @property permissions - POSIX-style permission string (e.g. "rwxr-xr-x"), or null.
 * @property mime_type   - Detected MIME type for files (e.g. "image/png"), or null.
 */
export interface Entry {
  path: string;
  name: string;
  size: number;
  modified: number | null;
  created: number | null;
  is_dir: boolean;
  permissions: string | null;
  mime_type: string | null;
}

/**
 * Parameters for a full-text / glob search across one or more disks.
 *
 * @property pattern   - The search pattern (interpreted by the backend index).
 * @property disk_ids  - If non-null, restricts search to these disk IDs. Null means search all.
 * @property recursive - When true, searches subdirectories recursively.
 */
export interface SearchQuery {
  pattern: string;
  disk_ids: string[] | null;
  recursive: boolean;
}

/**
 * A group of search hits originating from a single disk.
 * The backend returns one `SearchResult` per disk that had matches.
 *
 * @property disk_id   - ID of the disk these results belong to.
 * @property disk_name - Display name of the disk (avoids a separate lookup).
 * @property entries   - Matched entries within this disk.
 */
export interface SearchResult {
  disk_id: string;
  disk_name: string;
  entries: Entry[];
}

/**
 * Status of the search index for a single disk.
 * Used by the UI to show indexing progress or staleness warnings.
 *
 * @property disk_id      - The disk this status refers to.
 * @property status       - "stale" = needs reindex, "indexing" = in progress, "ready" = up-to-date.
 * @property entry_count  - Number of entries currently in the index.
 * @property last_indexed - ISO 8601 timestamp of the last successful index run, or null if never indexed.
 */
export interface IndexStatus {
  disk_id: string;
  status: "stale" | "indexing" | "ready";
  entry_count: number;
  last_indexed: string | null;
}

/** What kind of work a job performs. */
export type JobKind = "copy" | "move" | "delete";

/** Lifecycle status of a job. */
export type JobStatus = "running" | "completed" | "failed" | "cancelled";

/**
 * Snapshot of a backend job's state, received via "job-update" events.
 *
 * The backend emits a `JobInfo` payload on every progress tick for a
 * spawned background task (copy, move, delete). The frontend keeps a
 * reactive mirror of these snapshots in `JobContext`.
 *
 * @property id           - Unique job identifier assigned by the backend.
 * @property kind         - The type of bulk operation this job performs.
 * @property status       - Current lifecycle phase.
 * @property completed    - Number of items processed so far.
 * @property total        - Total number of items in this job.
 * @property description  - Human-readable summary, e.g. "readme.md → /Documents".
 * @property current_item - Path of the item currently being processed.
 * @property error        - Error message if the job failed, otherwise null.
 * @property created_at   - Unix timestamp (seconds) when the job was created.
 */
export interface JobInfo {
  id: string;
  kind: JobKind;
  status: JobStatus;
  completed: number;
  total: number;
  description: string;
  current_item: string;
  error: string | null;
  created_at: number;
  /** Disk ID where the job's effects land (for auto-refresh). */
  disk_id: string;
  /** Directory path where the job writes/deletes entries (for auto-refresh). */
  target_path: string;
}

/**
 * A pinned directory path for quick-access navigation.
 *
 * @property id         - UUID generated by the backend on creation.
 * @property disk_id    - ID of the disk this bookmark references.
 * @property disk_name  - Display name of the disk at the time of bookmarking.
 * @property path       - Storage-relative path to the bookmarked directory.
 * @property label      - User-facing label displayed in the sidebar.
 * @property created_at - ISO 8601 timestamp of when the bookmark was created.
 */
export interface Bookmark {
  id: string;
  disk_id: string;
  disk_name: string;
  path: string;
  label: string;
  created_at: string;
}

/**
 * Comparison status of a file in a directory diff.
 * - "added": exists only in the source directory.
 * - "removed": exists only in the destination directory.
 * - "modified": exists in both but differs (size or modified time).
 * - "unchanged": exists in both and is identical.
 */
export type DiffStatus = "added" | "removed" | "modified" | "unchanged";

/**
 * A single entry in a directory diff result.
 *
 * @property path         - Virtual path relative to the comparison root.
 * @property name         - Filename or directory name.
 * @property status       - Whether the entry is added, removed, modified, or unchanged.
 * @property is_dir       - True if the entry is a directory.
 * @property src_size     - Size in bytes on the source side, or null if absent.
 * @property dst_size     - Size in bytes on the destination side, or null if absent.
 * @property src_modified - Modification timestamp on the source side, or null.
 * @property dst_modified - Modification timestamp on the destination side, or null.
 */
export interface DiffEntry {
  path: string;
  name: string;
  status: DiffStatus;
  is_dir: boolean;
  src_size: number | null;
  dst_size: number | null;
  src_modified: number | null;
  dst_modified: number | null;
}

/**
 * A single entry in a directory size breakdown, returned by the
 * `get_size_breakdown` backend command. Used by the treemap visualization.
 *
 * @property path   - Virtual storage-relative path.
 * @property name   - Basename of the entry.
 * @property size   - Size in bytes (recursive for directories).
 * @property is_dir - True if the entry is a directory.
 */
export interface SizeEntry {
  path: string;
  name: string;
  size: number;
  is_dir: boolean;
}

/**
 * Payload emitted by the backend when a filesystem change is detected
 * in a watched directory.
 *
 * @property disk_id - ID of the disk where the change occurred.
 * @property path    - Storage-relative directory path being watched.
 * @property kind    - Kind of change: "create", "modify", or "delete".
 */
export interface FsChangeEvent {
  disk_id: string;
  path: string;
  kind: "create" | "modify" | "delete";
}

/** A tab in the main panel — either a directory browser or a file preview. */
export type Tab =
  | { kind: "browser"; id: string; diskId: string; diskName: string; currentPath: string }
  | {
      kind: "preview";
      id: string;
      diskId: string;
      path: string;
      name: string;
      mimeType: string | null;
    };

/** State of a loaded file preview. */
export type PreviewData =
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "text"; content: string }
  | { status: "image"; blobUrl: string; mimeType: string }
  | { status: "binary"; size: number; mimeType: string | null; modified: number | null };
